name: Test CiCd
on: 
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  check-cicd:
    name: Check cicd
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.11.0'

      - name: Install dependencies
        run: npm ci
      - name: Run Api Tests
        run:  npm run test